interface ObjectWithArrays {
  [key: string]: string[];
}
export const countriesCodes: ObjectWithArrays = {
  AD: ["Andorra", "Andorra"],
  AE: ["United Arab Emirates", "United Arab Emirates"],
  AF: ["Afghanistan", "Afghanistan"],
  AG: ["Antigua & Barbuda", "Antigua and Barbuda"],
  AI: ["Anguilla", "Anguilla"],
  AL: ["Albania", "Albania"],
  AM: ["Armenia", "Armenia"],
  AN: ["Netherlands Antilles", "Netherlands Antilles"],
  AO: ["Angola", "Angola"],
  AQ: ["Antarctica", "Antarctica"],
  AR: ["Argentina", "Argentina"],
  AS: ["American Samoa", "American Samoa"],
  AT: ["Austria", "Austria"],
  AU: ["Australia", "Australia"],
  AW: ["Aruba", "Aruba"],
  AZ: ["Azerbaijan", "Azerbaijan"],
  BA: ["Bosnia & Herzegovina", "Bosnia and Herzegovina"],
  BB: ["Barbados", "Barbados"],
  BD: ["Bangladesh", "Bangladesh"],
  BE: ["Belgium", "Belgium"],
  BF: ["Burkina Faso", "Burkina Faso"],
  BG: ["Bulgaria", "Bulgaria"],
  BH: ["Bahrain", "Bahrain"],
  BI: ["Burundi", "Burundi"],
  BJ: ["Benin", "Benin"],
  BM: ["Bermuda", "Bermuda"],
  BN: ["Brunei", "Brunei Darussalam"],
  BO: ["Bolivia", "Bolivia"],
  BR: ["Brazil", "Brazil"],
  BS: ["Bahamas", "Bahamas"],
  BT: ["Bhutan", "Bhutan"],
  BU: ["Burma", "Burma"],
  BV: ["Bouvet Island", "Bouvet Island"],
  BW: ["Botswana", "Botswana"],
  BY: ["Belarus", "Belarus"],
  BZ: ["Belize", "Belize"],
  CA: ["Canada", "Canada"],
  CC: ["Cocos (Keeling) Islands", "Cocos  Islands"],
  CD: ["Democratic Republic of the Congo (Kinshasa)", "Congo"],
  CF: ["Central African Republic", "Central African Republic"],
  CG: ["Republic of the Congo (Brazzaville)", "Congo"],
  CH: ["Switzerland", "Switzerland"],
  CI: ["Côte d’Ivoire", "Cote D'Ivoire"],
  CK: ["Cook Islands", "Cook Islands"],
  CL: ["Chile", "Chile"],
  CM: ["Cameroon", "Cameroon"],
  CN: ["China", "China"],
  CO: ["Colombia", "Colombia"],
  CR: ["Costa Rica", "Costa Rica"],
  CS: ["Serbia and Montenegro", "Serbia and Montenegro"],
  CU: ["Cuba", "Cuba"],
  CV: ["Cape Verde", "Cape Verde"],
  CX: ["Christmas Island", "Christmas Island"],
  CY: ["Cyprus", "Cyprus"],
  CZ: ["Czech Republic", "Czech Republic"],
  DE: ["Germany", "Germany"],
  DJ: ["Djibouti", "Djibouti"],
  DK: ["Denmark", "Denmark"],
  DM: ["Dominica", "Dominica"],
  DO: ["Dominican Republic", "Dominican Republic"],
  DZ: ["Algeria", "Algeria"],
  EC: ["Ecuador", "Ecuador"],
  EE: ["Estonia", "Estonia"],
  EG: ["Egypt", "Egypt"],
  EH: ["Western Sahara", "Western Sahara"],
  ER: ["Eritrea", "Eritrea"],
  ES: ["Spain", "Spain"],
  ET: ["Ethiopia", "Ethiopia"],
  FI: ["Finland", "Finland"],
  FJ: ["Fiji", "Fiji"],
  FK: ["Falkland Islands", "Falkland Islands"],
  FM: ["Micronesia", "Micronesia"],
  FO: ["Faroe Islands", "Faeroe Islands"],
  FR: ["France", "France"],
  GA: ["Gabon", "Gabon"],
  GB: ["United Kingdom", "United Kingdom"],
  GD: ["Grenada", "Grenada"],
  GE: ["Georgia", "Georgia"],
  GF: ["French Guiana", "French Guiana"],
  GH: ["Ghana", "Ghana"],
  GI: ["Gibraltar", "Gibraltar"],
  GL: ["Greenland", "Greenland"],
  GM: ["Gambia", "Gambia"],
  GN: ["Guinea", "Guinea"],
  GP: ["Guadeloupe", "Guadaloupe"],
  GQ: ["Equatorial Guinea", "Equatorial Guinea"],
  GR: ["Greece", "Greece"],
  GS: [
    "South Georgia & South Sandwich Islands",
    "South Georgia and the South Sandwich Islands",
  ],
  GT: ["Guatemala", "Guatemala"],
  GU: ["Guam", "Guam"],
  GW: ["Guinea-Bissau", "Guinea-Bissau"],
  GY: ["Guyana", "Guyana"],
  HK: ["Hong Kong SAR China", "Hong Kong"],
  HM: ["Heard & McDonald Islands", "Heard and McDonald Islands"],
  HN: ["Honduras", "Honduras"],
  HR: ["Croatia", "Croatia"],
  HT: ["Haiti", "Haiti"],
  HU: ["Hungary", "Hungary"],
  ID: ["Indonesia", "Indonesia"],
  IE: ["Ireland", "Ireland"],
  IL: ["Israel", "Israel"],
  IN: ["India", "India"],
  IO: ["British Indian Ocean Territory", "British Indian Ocean Territory"],
  IQ: ["Iraq", "Iraq"],
  IR: ["Iran", "Iran"],
  IS: ["Iceland", "Iceland"],
  IT: ["Italy", "Italy"],
  JM: ["Jamaica", "Jamaica"],
  JO: ["Jordan", "Jordan"],
  JP: ["Japan", "Japan"],
  KE: ["Kenya", "Kenya"],
  KG: ["Kyrgyzstan", "Kyrgyz Republic"],
  KH: ["Cambodia", "Cambodia"],
  KI: ["Kiribati", "Kiribati"],
  KM: ["Comoros", "Comoros"],
  KN: ["St. Kitts & Nevis", "St. Kitts and Nevis"],
  KP: ["North Korea", "North Korea"],
  KR: ["South Korea", "South Korea"],
  KW: ["Kuwait", "Kuwait"],
  KY: ["Cayman Islands", "Cayman Islands"],
  KZ: ["Kazakhstan", "Kazakhstan"],
  LA: ["Laos", "Lao People's Democratic Republic"],
  LB: ["Lebanon", "Lebanon"],
  LC: ["St. Lucia", "St. Lucia"],
  LI: ["Liechtenstein", "Liechtenstein"],
  LK: ["Sri Lanka", "Sri Lanka"],
  LR: ["Liberia", "Liberia"],
  LS: ["Lesotho", "Lesotho"],
  LT: ["Lithuania", "Lithuania"],
  LU: ["Luxembourg", "Luxembourg"],
  LV: ["Latvia", "Latvia"],
  LY: ["Libya", "Libyan Arab Jamahiriya"],
  MA: ["Morocco", "Morocco"],
  MC: ["Monaco", "Monaco"],
  MD: ["Moldova", "Moldova"],
  ME: ["Montenegro", "Montenegro"],
  MG: ["Madagascar", "Madagascar"],
  MH: ["Marshall Islands", "Marshall Islands"],
  MK: ["Macedonia", "Macedonia"],
  ML: ["Mali", "Mali"],
  MM: ["Myanmar (Burma)", "Myanmar"],
  MN: ["Mongolia", "Mongolia"],
  MO: ["Macau SAR China", "Macao"],
  MP: ["Northern Mariana Islands", "Northern Mariana Islands"],
  MQ: ["Martinique", "Martinique"],
  MR: ["Mauritania", "Mauritania"],
  MS: ["Montserrat", "Montserrat"],
  MT: ["Malta", "Malta"],
  MU: ["Mauritius", "Mauritius"],
  MV: ["Maldives", "Maldives"],
  MW: ["Malawi", "Malawi"],
  MX: ["Mexico", "Mexico"],
  MY: ["Malaysia", "Malaysia"],
  MZ: ["Mozambique", "Mozambique"],
  NA: ["Namibia", "Namibia"],
  NC: ["New Caledonia", "New Caledonia"],
  NE: ["Niger", "Niger"],
  NF: ["Norfolk Island", "Norfolk Island"],
  NG: ["Nigeria", "Nigeria"],
  NI: ["Nicaragua", "Nicaragua"],
  NL: ["Netherlands", "Netherlands"],
  NO: ["Norway", "Norway"],
  NP: ["Nepal", "Nepal"],
  NR: ["Nauru", "Nauru"],
  NU: ["Niue", "Niue"],
  NZ: ["New Zealand", "New Zealand"],
  OM: ["Oman", "Oman"],
  PA: ["Panama", "Panama"],
  PE: ["Peru", "Peru"],
  PF: ["French Polynesia", "French Polynesia"],
  PG: ["Papua New Guinea", "Papua New Guinea"],
  PH: ["Philippines", "Philippines"],
  PK: ["Pakistan", "Pakistan"],
  PL: ["Poland", "Poland"],
  PM: ["St. Pierre & Miquelon", "St. Pierre and Miquelon"],
  PN: ["Pitcairn Islands", "Pitcairn Island"],
  PR: ["Puerto Rico", "Puerto Rico"],
  PS: ["Palestinian Territories", "Palestinian Territory"],
  PT: ["Portugal", "Portugal"],
  PW: ["Palau", "Palau"],
  PY: ["Paraguay", "Paraguay"],
  QA: ["Qatar", "Qatar"],
  RE: ["Réunion", "Reunion"],
  RO: ["Romania", "Romania"],
  RS: ["Serbia", "Serbia"],
  RU: ["Russia", "Russia"],
  RW: ["Rwanda", "Rwanda"],
  SA: ["Saudi Arabia", "Saudi Arabia"],
  SB: ["Solomon Islands", "Solomon Islands"],
  SC: ["Seychelles", "Seychelles"],
  SD: ["Sudan", "Sudan"],
  SE: ["Sweden", "Sweden"],
  SG: ["Singapore", "Singapore"],
  SH: ["St. Helena", "St. Helena"],
  SI: ["Slovenia", "Slovenia"],
  SJ: ["Svalbard & Jan Mayen", "Svalbard & Jan Mayen Islands"],
  SK: ["Slovakia", "Slovakia"],
  SL: ["Sierra Leone", "Sierra Leone"],
  SM: ["San Marino", "San Marino"],
  SN: ["Senegal", "Senegal"],
  SO: ["Somalia", "Somalia"],
  SR: ["Suriname", "Suriname"],
  SS: ["South Sudan", "South Sudan"],
  ST: ["São Tomé & Príncipe", "Sao Tome and Principe"],
  SU: ["Soviet Union", "Soviet Union"],
  SV: ["El Salvador", "El Salvador"],
  SY: ["Syria", "Syrian Arab Republic"],
  SZ: ["Eswatini (Swaziland)", "Swaziland"],
  TC: ["Turks & Caicos Islands", "Turks and Caicos Islands"],
  TD: ["Chad", "Chad"],
  TF: ["French Southern Territories", "French Southern Territories"],
  TG: ["Togo", "Togo"],
  TH: ["Thailand", "Thailand"],
  TJ: ["Tajikistan", "Tajikistan"],
  TK: ["Tokelau", "Tokelau"],
  TL: ["Timor-Leste", "Timor-Leste"],
  TM: ["Turkmenistan", "Turkmenistan"],
  TN: ["Tunisia", "Tunisia"],
  TO: ["Tonga", "Tonga"],
  TP: ["East Timor", "East Timor"],
  TR: ["Turkey", "Turkey"],
  TT: ["Trinidad & Tobago", "Trinidad and Tobago"],
  TV: ["Tuvalu", "Tuvalu"],
  TW: ["Taiwan", "Taiwan"],
  TZ: ["Tanzania", "Tanzania"],
  UA: ["Ukraine", "Ukraine"],
  UG: ["Uganda", "Uganda"],
  UM: ["U.S. Outlying Islands", "United States Minor Outlying Islands"],
  US: ["United States", "United States of America"],
  UY: ["Uruguay", "Uruguay"],
  UZ: ["Uzbekistan", "Uzbekistan"],
  VA: ["Vatican City", "Holy See"],
  VC: ["St. Vincent & Grenadines", "St. Vincent and the Grenadines"],
  VE: ["Venezuela", "Venezuela"],
  VG: ["British Virgin Islands", "British Virgin Islands"],
  VI: ["U.S. Virgin Islands", "US Virgin Islands"],
  VN: ["Vietnam", "Vietnam"],
  VU: ["Vanuatu", "Vanuatu"],
  WF: ["Wallis & Futuna", "Wallis and Futuna Islands"],
  WS: ["Samoa", "Samoa"],
  XC: ["Czechoslovakia", "Czechoslovakia"],
  XG: ["East Germany", "East Germany"],
  XI: ["Northern Ireland", "Northern Ireland"],
  XK: ["Kosovo", "Kosovo"],
  YE: ["Yemen", "Yemen"],
  YT: ["Mayotte", "Mayotte"],
  YU: ["Yugoslavia", "Yugoslavia"],
  ZA: ["South Africa", "South Africa"],
  ZM: ["Zambia", "Zambia"],
  ZR: ["Zaire", "Zaire"],
  ZW: ["Zimbabwe", "Zimbabwe"],
};

export const languagesCodes: ObjectWithArrays = {
  aa: ["Afar"],
  af: ["Afrikaans", "Afrikaans"],
  ak: ["Akan"],
  an: ["Aragonese"],
  as: ["Assamese"],
  av: ["Avaric"],
  ae: ["Avestan"],
  ay: ["Aymara"],
  az: ["Azərbaycan", "Azerbaijani"],
  ba: ["Bashkir"],
  bm: ["Bamanankan", "Bambara"],
  bi: ["Bislama"],
  bo: ["Tibetan"],
  br: ["Breton"],
  ca: ["Català", "Catalan"],
  cs: ["Český", "Czech"],
  ce: ["Chechen"],
  cu: ["Slavic"],
  cv: ["Chuvash"],
  kw: ["Cornish"],
  co: ["Corsican"],
  cr: ["Cree"],
  cy: ["Cymraeg", "Welsh"],
  da: ["Dansk", "Danish"],
  de: ["Deutsch", "German"],
  dv: ["Divehi"],
  dz: ["Dzongkha"],
  eo: ["Esperanto", "Esperanto"],
  et: ["Eesti", "Estonian"],
  eu: ["euskera", "Basque"],
  fo: ["Faroese"],
  fj: ["Fijian"],
  fi: ["suomi", "Finnish"],
  fr: ["Français", "French"],
  fy: ["Frisian"],
  ff: ["Fulfulde", "Fulah"],
  gd: ["Gaelic"],
  ga: ["Gaeilge", "Irish"],
  gl: ["Galego", "Galician"],
  gv: ["Manx"],
  gn: ["Guarani"],
  gu: ["Gujarati"],
  ht: ["Haitian; Haitian Creole"],
  ha: ["Hausa", "Hausa"],
  sh: ["Serbo-Croatian"],
  hz: ["Herero"],
  ho: ["Hiri Motu"],
  hr: ["Hrvatski", "Croatian"],
  hu: ["Magyar", "Hungarian"],
  ig: ["Igbo"],
  io: ["Ido"],
  ii: ["Yi"],
  iu: ["Inuktitut"],
  ie: ["Interlingue"],
  ia: ["Interlingua"],
  id: ["Bahasa indonesia", "Indonesian"],
  ik: ["Inupiaq"],
  is: ["Íslenska", "Icelandic"],
  it: ["Italiano", "Italian"],
  jv: ["Javanese"],
  ja: ["日本語", "Japanese"],
  kl: ["Kalaallisut"],
  kn: ["?????", "Kannada"],
  ks: ["Kashmiri"],
  kr: ["Kanuri"],
  kk: ["қазақ", "Kazakh"],
  km: ["Khmer"],
  ki: ["Kikuyu"],
  rw: ["Kinyarwanda", "Kinyarwanda"],
  ky: ["??????", "Kirghiz"],
  kv: ["Komi"],
  kg: ["Kongo"],
  ko: ["한국어/조선말", "Korean"],
  kj: ["Kuanyama"],
  ku: ["Kurdish"],
  lo: ["Lao"],
  la: ["Latin", "Latin"],
  lv: ["Latviešu", "Latvian"],
  li: ["Limburgish"],
  ln: ["Lingala"],
  lt: ["Lietuvių", "Lithuanian"],
  lb: ["Letzeburgesch"],
  lu: ["Luba-Katanga"],
  lg: ["Ganda"],
  mh: ["Marshall"],
  ml: ["Malayalam"],
  mr: ["Marathi"],
  mg: ["Malagasy"],
  mt: ["Malti", "Maltese"],
  mo: ["Moldavian"],
  mn: ["Mongolian"],
  mi: ["Maori"],
  ms: ["Bahasa melayu", "Malay"],
  my: ["Burmese"],
  na: ["Nauru"],
  nv: ["Navajo"],
  nr: ["Ndebele"],
  nd: ["Ndebele"],
  ng: ["Ndonga"],
  ne: ["Nepali"],
  nl: ["Nederlands", "Dutch"],
  nn: ["Norwegian Nynorsk"],
  nb: ["Bokmål", "Norwegian Bokmål"],
  no: ["Norsk", "Norwegian"],
  ny: ["Chichewa; Nyanja"],
  oc: ["Occitan"],
  oj: ["Ojibwa"],
  or: ["Oriya"],
  om: ["Oromo"],
  os: ["Ossetian; Ossetic"],
  pi: ["Pali"],
  pl: ["Polski", "Polish"],
  pt: ["Português", "Portuguese"],
  qu: ["Quechua"],
  rm: ["Raeto-Romance"],
  ro: ["Română", "Romanian"],
  rn: ["Kirundi", "Rundi"],
  ru: ["Pусский", "Russian"],
  sg: ["Sango"],
  sa: ["Sanskrit"],
  si: ["සිංහල", "Sinhalese"],
  sk: ["Slovenčina", "Slovak"],
  sl: ["Slovenščina", "Slovenian"],
  se: ["Northern Sami"],
  sm: ["Samoan"],
  sn: ["Shona"],
  sd: ["Sindhi"],
  so: ["Somali", "Somali"],
  st: ["Sotho"],
  es: ["Español", "Spanish"],
  sq: ["shqip", "Albanian"],
  sc: ["Sardinian"],
  sr: ["Srpski", "Serbian"],
  ss: ["Swati"],
  su: ["Sundanese"],
  sw: ["Kiswahili", "Swahili"],
  sv: ["svenska", "Swedish"],
  ty: ["Tahitian"],
  ta: ["தமிழ்", "Tamil"],
  tt: ["Tatar"],
  te: ["తెలుగు", "Telugu"],
  tg: ["Tajik"],
  tl: ["Tagalog"],
  th: ["ภาษาไทย", "Thai"],
  ti: ["Tigrinya"],
  to: ["Tonga"],
  tn: ["Tswana"],
  ts: ["Tsonga"],
  tk: ["Turkmen"],
  tr: ["Türkçe", "Turkish"],
  tw: ["Twi"],
  ug: ["Uighur"],
  uk: ["Український", "Ukrainian"],
  ur: ["اردو", "Urdu"],
  uz: ["ozbek", "Uzbek"],
  ve: ["Venda"],
  vi: ["Tiếng Việt", "Vietnamese"],
  vo: ["Volapük"],
  wa: ["Walloon"],
  wo: ["Wolof", "Wolof"],
  xh: ["Xhosa"],
  yi: ["Yiddish"],
  za: ["Zhuang"],
  zu: ["isiZulu", "Zulu"],
  ab: ["Abkhazian"],
  zh: ["普通话", "Mandarin"],
  ps: ["پښتو", "Pushto"],
  am: ["Amharic"],
  ar: ["العربية", "Arabic"],
  bg: ["български език", "Bulgarian"],
  cn: ["广州话 / 廣州話", "Cantonese"],
  mk: ["Macedonian"],
  el: ["ελληνικά", "Greek"],
  fa: ["فارسی", "Persian"],
  he: ["עִבְרִית", "Hebrew"],
  hi: ["हिन्दी", "Hindi"],
  hy: ["Armenian"],
  en: ["English", "English"],
  ee: ["Èʋegbe", "Ewe"],
  ka: ["ქართული", "Georgian"],
  pa: ["ਪੰਜਾਬੀ", "Punjabi"],
  bn: ["বাংলা", "Bengali"],
  bs: ["Bosanski", "Bosnian"],
  ch: ["Finu' Chamorro", "Chamorro"],
  be: ["беларуская мова", "Belarusian"],
  yo: ["Èdè Yorùbá", "Yoruba"],
};

export const youtubePrefix = "https://www.youtube.com/watch?v=";
export const tmbdImagesPrefix = "https://image.tmdb.org/t/p/";

export const imgBackdropSizes = ["w300", "w780", "w1280", "original"];
export const imgLogoSizes = [
  "w45",
  "w92",
  "w154",
  "w185",
  "w300",
  "w500",
  "original",
];
export const imgPosterSizes = [
  "w92",
  "w154",
  "w185",
  "w342",
  "w500",
  "w780",
  "original",
];
export const imgProfileSizes = ["w45", "w185", "h632", "original"];
export const imgStillSizes = ["w92", "w185", "w300", "original"];
